object BaseFrame: TBaseFrame
  Left = 0
  Top = 0
  Width = 908
  Height = 611
  VertScrollBar.ButtonSize = 20
  VertScrollBar.Margin = 20
  VertScrollBar.Range = 500
  VertScrollBar.Smooth = True
  VertScrollBar.Size = 20
  VertScrollBar.ThumbSize = 20
  VertScrollBar.Tracking = True
  DoubleBuffered = True
  Color = 12511226
  ParentBackground = False
  ParentColor = False
  ParentDoubleBuffered = False
  TabOrder = 0
end
